// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.MyRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemlefttalon1;
    public static SpeedController driveSystemlefttalon2;
    public static SpeedControllerGroup driveSystemlefttalons;
    public static SpeedController driveSystemrighttalon1;
    public static SpeedController driveSystemrighttalon2;
    public static SpeedControllerGroup driveSystemrighttalons;
    public static RobotDrive driveSystemRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemlefttalon1 = new Talon(4);
        LiveWindow.addActuator("DriveSystem", "left talon 1", (Talon) driveSystemlefttalon1);
        driveSystemlefttalon1.setInverted(false);
        driveSystemlefttalon2 = new Talon(1);
        LiveWindow.addActuator("DriveSystem", "left talon 2", (Talon) driveSystemlefttalon2);
        driveSystemlefttalon2.setInverted(false);
        driveSystemlefttalons = new SpeedControllerGroup(driveSystemlefttalon1, driveSystemlefttalon2  );
        LiveWindow.addActuator("DriveSystem", "left talons", driveSystemlefttalons);
        
        driveSystemrighttalon1 = new Talon(0);
        LiveWindow.addActuator("DriveSystem", "right talon 1", (Talon) driveSystemrighttalon1);
        driveSystemrighttalon1.setInverted(false);
        driveSystemrighttalon2 = new Talon(3);
        LiveWindow.addActuator("DriveSystem", "right talon 2", (Talon) driveSystemrighttalon2);
        driveSystemrighttalon2.setInverted(false);
        driveSystemrighttalons = new SpeedControllerGroup(driveSystemrighttalon1, driveSystemrighttalon2  );
        LiveWindow.addActuator("DriveSystem", "right talons", driveSystemrighttalons);
        
        driveSystemRobotDrive21 = new RobotDrive(driveSystemlefttalons, driveSystemlefttalon2);
        
        driveSystemRobotDrive21.setSafetyEnabled(true);
        driveSystemRobotDrive21.setExpiration(0.1);
        driveSystemRobotDrive21.setSensitivity(0.5);
        driveSystemRobotDrive21.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
